# Generated by Django 4.1.1 on 2022-09-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_orders_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='orders',
            new_name='order',
        ),
    ]
