# Generated by Django 4.1.1 on 2022-09-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_update',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_description', models.CharField(max_length=5000)),
                ('timestemp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
